{
 "title": "Vulnerability Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App-specific vulnerabilities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "All Vulnerabilities in app namespace",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{resource_namespace=\"app\"})"
    }
   ]
  },
  {
   "title": "All vulnerabilities in ns app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{resource_namespace=\"app\",severity=\"MEDIUM\"})",
     "legendFormat": "MEDIUM"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{resource_namespace=\"app\",severity=\"CRITICAL\"})",
     "legendFormat": "CRITICAL"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{resource_namespace=\"app\",severity=\"HIGH\"})",
     "legendFormat": "HIGH"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{resource_namespace=\"app\",severity=\"LOW\"})",
     "legendFormat": "LOW"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{resource_namespace=\"app\"})",
     "legendFormat": "ALL"
    }
   ]
  },
  { "title": "Cluster-wide vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Summary of all vulnerabilities",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"CRITICAL\"})",
     "legendFormat": "CRITICAL"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"HIGH\"})",
     "legendFormat": "HIGH"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"MEDIUM\"})",
     "legendFormat": "MEDIUM"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"LOW\"})",
     "legendFormat": "LOW"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{})",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Summary of all vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"CRITICAL\"})",
     "legendFormat": "CRITICAL"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"HIGH\"})",
     "legendFormat": "HIGH"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"MEDIUM\"})",
     "legendFormat": "MEDIUM"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"LOW\"})",
     "legendFormat": "LOW"
    },
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{})",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "LOW Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"LOW\"})"
    }
   ]
  },
  {
   "title": "CRITICAL Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"CRITICAL\"})"
    }
   ]
  },
  {
   "title": "MEDIUM Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"MEDIUM\"})"
    }
   ]
  },
  {
   "title": "HIGH vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starboard_exporter_configauditreport_resource_checks_summary_count{severity=\"HIGH\"})"
    }
   ]
  }
 ]
}